steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/hidden-terrain-369021/project', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/hidden-terrain-369021/project']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'project', '--image', 'gcr.io/hidden-terrain-369021/project', '--region', 'us-central1', '--platform', 'managed','--port','80']
images:
- gcr.io/hidden-terrain-369021/project